---
# tasks file for php5-fpm-debian

- name: Check if php5-fpm is already installed
  command: dpkg -s php5-fpm
  ignore_errors: yes
  register: result
  failed_when: result.stderr.find('is not installed') != -1

# Add php5 repository if never done before
- name: Add php5 repository
  apt_repository: repo='deb http://packages.dotdeb.org {{ansible_distribution_release}}-php55 all' state=present
  when: result|failed

# Add php5 repository key to apt keyring if never done before
- name: Add php5 repository key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  when: result|failed

# Refresh apt packages if the php5 repo has just been added
- name: Update apt
  apt: update_cache=yes
  when: result|failed

# Install and upgrades the packages
- name: Install PHP Packages
  apt: pkg={{item}} state=latest
  with_items: php_packages

# Install phpmyadmin if specified
- name: Install phpmyadmin Package
  apt: pkg=phpmyadmin state=latest
  when: install_phpmyadmin == true

# Users stuff
- name: Set nginx user as owner for /var/run/php5-fpm.sock
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='listen.owner' line='listen.owner = {{nginx_user}}' state=present

- name: Set nginx group as group for /var/run/php5-fpm.sock
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='listen.group' line='listen.group = {{nginx_user}}' state=present

- name: Set php5fpm default user as "{{nginx_user}}"
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='^user =' line='user = {{nginx_user}}' state=present

- name: Set php5fpm default group as "{{nginx_group}}"
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='^group =' line='group = {{nginx_group}}' state=present

- name: Enable TCP/IP instead of unix socket
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp='^listen =' line='listen = 127.0.0.1:9000' state=present
  when: use_tcp_ip_connection == true

- service: name=php5-fpm state=restarted enabled=yes
